type = "Project"
name = "Polarimeter_Project"
description = ""
version = "1.0.0"
author = ""
created = '2014-08-17T14:58:57.600623+00:00'
modified = '2014-08-17T14:58:57.600623+00:00'
componentsList = ["Source.Source_1", "Polariser.Polariser_1", "Retarder.Retarder_1"]

[[components]]
type = "Source"
name = "SoP1"
description = ""
theta = 45.0
radians = false
lambdaPresent = 6563.0
mueller = [ [1.0], [0.0], [-1.0], [0.0]]
jones = [[1.0], [1.0]]
color = "white"
enabled = true


[[components]]
type = "Source"
name = "SoP2"
description = ""
theta = 30.0
radians = false
lambdaPresent = 6563.0
mueller = [ [1.0], [0.0], [0.0], [-1.0]]
jones = [[1.0], [1.0]]
color = "white"
enabled = true

[[components]]
type = "Retarder"
name = "R1"
description = "Single retarder"
delta = 60.0
theta = 20.0
lambdaPresent = 6563.0
lambda0 = 6563.0
radians = false
mueller = [ [ 1.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,]]
jones = [ [ 1.0, 1.0,], [ 1.0, 1.0,]]
color = "green"
enabled = true

[[components]]
type = "Retarder"
name = "R2"
description = "Double retarder"
delta = 130.0
theta = 60.0
radians = false
lambdaPresent = 6000.0
lambda0 = 3000.0
mueller = [ [ 1.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,]]
jones = [ [ 1.0, 1.0,], [ 1.0, 1.0,]]
color = "yellow"
enabled = true

[[components]]
type = "Polariser"
name = "Analyser"
description = ""
theta = 45.0
radians = false
mueller = [ [ 1.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0, 0.0,]]
jones = [ [ 1.0, 1.0,], [ 1.0, 1.0,]]
color = "blue"
enabled = true

[[components]]
type = "Detector"
name = "Detector_1"
description = ""
color = "black"
enabled = true
