# -*- coding: utf-8 -*-
"""
Optics Lab GUI - wxPython + VisPy
Clean corrected version. Uses project classes/functions directly - no hardcoding.
"""

import wx
import wx.propgrid as pg
import numpy as np
import os
import sys
import json
import re

# ── VisPy backend must be set before any vispy import ──────────────────────────
import vispy.app
vispy.app.use_app('wx')

from vispy import scene
from vispy.color import Color

# ── GUI base (generated by wxFormBuilder – do not edit) ────────────────────────
from opticsguiproject_gui import MainFrameBase

# ── VisPy plot canvas wrapper ──────────────────────────────────────────────────
from wx_VispyPlotCanvas import wx_VispyPlotCanvas

# ── Simulation back-end ────────────────────────────────────────────────────────
from opticsLAB.raytracing.component import OpticsLabCanvas, Z_AXIS_DIRECTION
from opticsLAB.raytracing.component.opticalPrimitives.Point         import Point
from opticsLAB.raytracing.component.opticalPrimitives.SphericalLens import SphericalLens
from opticsLAB.raytracing.component.opticalPrimitives.ParabolicLens import ParabolicLens
from opticsLAB.raytracing.component.opticalPrimitives.concaveParaboloid import Concave_Paraboloid
from opticsLAB.raytracing.component.opticalPrimitives.convexParaboloid  import Convex_Paraboloid
from opticsLAB.raytracing.component.primitives.parabolicSurface  import Parabolic_Surface
from opticsLAB.raytracing.component.primitives.sphericalSurface  import Spherical_Surface
from opticsLAB.raytracing.component.primitives.OpticalSystems    import OpticalSystem
from opticsLAB.raytracing.component.sources                      import Ray
from opticsLAB.raytracing.spotDiagram import SpotDiagramPlot, wavelength_to_rgb

# ── Material catalogue ─────────────────────────────────────────────────────────
from opticsLAB.raytracing.component.materialProperties import catalogue

# ── Fallback default component properties (also loaded from config JSON) ───────
DEFAULT_PROPERTIES = {
    'Spherical Lens': {
        'type': 'Spherical Lens', 'name': 'Spherical Lens',
        'center_z': 1.0, 'radius': 1.0, 'thickness': 0.6,
        'R1': 2.0, 'R2': -2.0,
        'mediumBefore': 'Air', 'mediumAfter': 'BK7', 'color': 'lightblue'
    },
    'Parabolic Lens': {
        'type': 'Parabolic Lens', 'name': 'Parabolic Lens',
        'center_z': 2.0, 'radius': 1.0, 'thickness': 0.5,
        'a': 1.0, 'b': 1.0, 'c_front': -1.0, 'c_back': 1.0,
        'mediumBefore': 'Air', 'mediumAfter': 'BK7', 'color': 'lightblue'
    },
    'Concave Paraboloid': {
        'type': 'Concave Paraboloid', 'name': 'Concave Paraboloid',
        'center_z': 3.0, 'radius': 1.0, 'a': 1.0, 'b': 1.0,
        'centerHoleRadius': 0.0, 'xTilt': 0.0, 'yTilt': 0.0,
        'mediumBefore': 'Air', 'mediumAfter': 'Air', 'color': 'lightgreen'
    },
    'Convex Paraboloid': {
        'type': 'Convex Paraboloid', 'name': 'Convex Paraboloid',
        'center_z': 3.0, 'radius': 1.0, 'a': 1.0, 'b': 1.0,
        'xTilt': 0.0, 'yTilt': 0.0,
        'mediumBefore': 'Air', 'mediumAfter': 'Air', 'color': 'lightgreen'
    },
    'Parabolic Surface': {
        'type': 'Parabolic Surface', 'name': 'Parabolic Surface',
        'center_z': 3.0, 'radius': 1.0, 'a': 1.0, 'b': 1.0, 'c': -1.0,
        'centerHoleRadius': 0.0, 'xTilt': 0.0, 'yTilt': 0.0,
        'mediumBefore': 'Air', 'mediumAfter': 'Air', 'color': 'lightgreen'
    },
    'Spherical Surface': {
        'type': 'Spherical Surface', 'name': 'Spherical Surface',
        'center_z': 3.0, 'radius_of_curvature': 5.0, 'radius': 1.0,
        'xTilt': 0.0, 'yTilt': 0.0,
        'mediumBefore': 'Air', 'mediumAfter': 'Air', 'color': 'lightgreen'
    },
}


# ══════════════════════════════════════════════════════════════════════════════
class OpticsLabGuiApp(MainFrameBase):
    """Main application window."""

    # ── init ──────────────────────────────────────────────────────────────────
    def __init__(self, parent):
        super().__init__(parent)

        # Component list and selection state
        self.components = []
        self.selected_index = -1

        # Global simulation settings
        self.global_settings = {
            'pupil_radius': 0.7,
            'z_image':      5.0,
            'auto_focus':   True,
            'z_start':     -2.0,
            'num_rays':     12,
        }

        # RGB wavelengths used for multi-colour tracing
        self.wavelengths = {
            'blue':  0.465,
            'green': 0.530,
            'red':   0.620,
        }

        # Progress gauge on toolbar
        self.gauge = wx.Gauge(self.m_toolBar1, wx.ID_ANY,
                              range=100, size=(150, -1),
                              style=wx.GA_HORIZONTAL)
        self.m_toolBar1.AddControl(self.gauge)
        self.m_toolBar1.Realize()

        # ── Sizers for the three canvas panels ────────────────────────────────
        self.canvas_sizer = wx.BoxSizer(wx.VERTICAL)
        self.m_panel_canvas_placeholder.SetSizer(self.canvas_sizer)

        self.spot_sizer = wx.BoxSizer(wx.VERTICAL)
        self.panel_SpotDiagram.SetSizer(self.spot_sizer)

        self.rayfan_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.panel_RayFanDiagram.SetSizer(self.rayfan_sizer)

        # ── 3-D optics canvas (VisPy inside wx panel) ─────────────────────────
        self.optics_canvas = OpticsLabCanvas(
            parent=self.m_panel_canvas_placeholder
        )
        self.canvas_sizer.Add(self.optics_canvas.canvas.native, 1, wx.EXPAND)
        self.optics_canvas.canvas.show()

        # Remember the "built-in" visuals so we can clear only user ones later
        self.base_visuals = set(self.optics_canvas.view.scene.children)

        # ── Extra event bindings ───────────────────────────────────────────────
        self.m_listBox_lst_components.Bind(
            wx.EVT_LISTBOX, self.m_listBox_lst_componentsOnSelect)
        self.m_listBox2.Bind(wx.EVT_LISTBOX, self.OnExampleSelect)
        self.propertyGrid_Properties.Bind(
            pg.EVT_PG_CHANGED, self.OnPropertyGridChange)

        # ── Populate built-in examples ────────────────────────────────────────
        self.m_listBox2.Append("Biconvex Lens Focus")
        self.m_listBox2.Append("Apochromatic Triplet")
        self.m_listBox2.Append("Cooke Triplet")

        # Start with empty state
        self.update_list_views()
        self.select_component(-1)
        self.m_statusBar1.SetStatusText(
            "Ready. Add a component or load a Python example to begin.")

    # ── Gauge animation ───────────────────────────────────────────────────────
    def animate_gauge(self):
        self.gauge.SetValue(0)
        for i in range(1, 101, 10):
            self.gauge.SetValue(i)
            wx.MilliSleep(30)
            wx.SafeYield()
        self.gauge.SetValue(100)
        wx.MilliSleep(50)
        self.gauge.SetValue(0)

    # ── Load default config from JSON (falls back to DEFAULT_PROPERTIES) ──────
    def _load_config(self, ctype):
        config_path = os.path.join("config", "default_lenses.json")
        try:
            with open(config_path, 'r') as f:
                return json.load(f)[ctype].copy()
        except Exception:
            return DEFAULT_PROPERTIES.get(ctype, {}).copy()

    # ══ Preset loaders ══════════════════════════════════════════════════════════
    def load_biconvex_preset(self):
        self.components = [{
            'type': 'Spherical Lens', 'name': 'Biconvex Lens',
            'center_z': 1.0, 'radius': 1.0, 'thickness': 0.6,
            'R1': 2.0, 'R2': -2.0,
            'mediumBefore': 'Air', 'mediumAfter': 'BK7', 'color': 'lightblue'
        }]
        self.global_settings = {
            'pupil_radius': 0.7, 'z_image': 3.8,
            'auto_focus': True, 'z_start': -2.0, 'num_rays': 12
        }

    def load_apochromatic_preset(self):
        self.components = [
            {'type': 'Spherical Lens', 'name': 'Front Lens',
             'center_z': -0.1635, 'radius': 1.0, 'thickness': 0.33,
             'R1': 4.4144, 'R2': -3.9524,
             'mediumBefore': 'Air', 'mediumAfter': 'fused silica',
             'color': 'lightblue'},
            {'type': 'Spherical Lens', 'name': 'Middle Lens',
             'center_z': 0.2667, 'radius': 1.0, 'thickness': 0.15,
             'R1': 15.8460, 'R2': -41.8801,
             'mediumBefore': 'Air', 'mediumAfter': 'sapphire',
             'color': 'lightcoral'},
            {'type': 'Spherical Lens', 'name': 'Rear Lens',
             'center_z': 0.4267, 'radius': 1.0, 'thickness': 0.15,
             'R1': 5.4845, 'R2': np.inf,
             'mediumBefore': 'Air', 'mediumAfter': 'BK7',
             'color': 'lightgreen'},
        ]
        self.global_settings = {
            'pupil_radius': 0.7, 'z_image': 2.8,
            'auto_focus': True, 'z_start': -2.0, 'num_rays': 12
        }

    def load_cooke_preset(self):
        t1, air1, t2, air2, t3 = 9.0, 10.0, 3.0, 13.0, 10.0
        z0 = 0.0
        z1_center = z0 + t1 / 2.0
        z2_front  = z0 + t1 + air1
        z2_center = z2_front + t2 / 2.0
        z3_front  = z2_front + t2 + air2
        z3_center = z3_front + t3 / 2.0
        self.components = [
            {'type': 'Spherical Lens', 'name': 'Cooke Front',
             'center_z': z1_center, 'radius': 20.0, 'thickness': t1,
             'R1': 34.94, 'R2': -1164.00,
             'mediumBefore': 'Air', 'mediumAfter': 'N-SK4',
             'color': 'lightblue'},
            {'type': 'Spherical Lens', 'name': 'Cooke Middle',
             'center_z': z2_center, 'radius': 10.35, 'thickness': t2,
             'R1': -60.369, 'R2': 30.68,
             'mediumBefore': 'Air', 'mediumAfter': 'N-SF2',
             'color': 'lightcoral'},
            {'type': 'Spherical Lens', 'name': 'Cooke Rear',
             'center_z': z3_center, 'radius': 20.0, 'thickness': t3,
             'R1': 91.77, 'R2': -49.08,
             'mediumBefore': 'Air', 'mediumAfter': 'N-SK4',
             'color': 'lightgreen'},
        ]
        self.global_settings = {
            'pupil_radius': 10.0,
            'z_image': z3_front + t3 + 75.98,
            'auto_focus': True, 'z_start': -20.0, 'num_rays': 12
        }

    # ══ UI helpers ══════════════════════════════════════════════════════════════
    def update_list_views(self):
        """Refresh ListBox and TreeCtrl from self.components."""
        self.m_listBox_lst_components.Clear()
        self.m_treeCtrl1.DeleteAllItems()
        self.tree_root = self.m_treeCtrl1.AddRoot("Optical System")
        for comp in self.components:
            label = f"{comp['name']} ({comp['type']})"
            self.m_listBox_lst_components.Append(label)
            self.m_treeCtrl1.AppendItem(self.tree_root, label)
        self.m_treeCtrl1.Expand(self.tree_root)

    def select_component(self, index):
        """Select a component by index (-1 = none / show global settings)."""
        self.selected_index = index
        if 0 <= index < self.m_listBox_lst_components.GetCount():
            self.m_listBox_lst_components.SetSelection(index)
        else:
            self.m_listBox_lst_components.SetSelection(wx.NOT_FOUND)

        if index >= 0:
            item, cookie = self.m_treeCtrl1.GetFirstChild(self.tree_root)
            curr = 0
            while item.IsOk():
                if curr == index:
                    self.m_treeCtrl1.SelectItem(item)
                    break
                item, cookie = self.m_treeCtrl1.GetNextChild(
                    self.tree_root, cookie)
                curr += 1
        else:
            self.m_treeCtrl1.SelectItem(self.tree_root)

        self.update_property_grid()

    def update_property_grid(self):
        """Populate the right-side PropertyGrid for the selected item."""
        self.propertyGrid_Properties.Clear()
        media_choices  = list(catalogue.keys())
        color_choices  = ['lightblue', 'lightgreen', 'lightcoral',
                          'yellow', 'tomato', 'teal', 'white', 'black']

        if self.selected_index < 0 or \
                self.selected_index >= len(self.components):
            # Show global simulation settings
            self.propertyGrid_Properties.Append(
                pg.PropertyCategory("Global Simulation Settings"))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Pupil Radius",  "pupil_radius",
                                 self.global_settings['pupil_radius']))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Source Z (z_start)", "z_start",
                                 self.global_settings['z_start']))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Image Plane Z", "z_image",
                                 self.global_settings['z_image']))
            self.propertyGrid_Properties.Append(
                pg.BoolProperty("Auto Focus", "auto_focus",
                                self.global_settings['auto_focus']))
            self.propertyGrid_Properties.Append(
                pg.IntProperty("Num Rays", "num_rays",
                               self.global_settings['num_rays']))
            return

        comp  = self.components[self.selected_index]
        ctype = comp['type']

        self.propertyGrid_Properties.Append(
            pg.PropertyCategory(f"{ctype} Properties"))
        self.propertyGrid_Properties.Append(
            pg.StringProperty("Name",      "name",     comp['name']))
        self.propertyGrid_Properties.Append(
            pg.FloatProperty("Center Z",   "center_z", comp['center_z']))
        self.propertyGrid_Properties.Append(
            pg.FloatProperty("Radius (Aperture)", "radius", comp['radius']))

        if ctype == 'Spherical Lens':
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("R1 Curvature (Front)", "R1",
                                 comp.get('R1', 2.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("R2 Curvature (Back)", "R2",
                                 comp.get('R2', -2.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Thickness", "thickness",
                                 comp.get('thickness', 0.6)))

        elif ctype == 'Parabolic Lens':
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("a Parameter", "a", comp.get('a', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("b Parameter", "b", comp.get('b', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("c Front (Sag)", "c_front",
                                 comp.get('c_front', -1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("c Back (Sag)", "c_back",
                                 comp.get('c_back', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Thickness", "thickness",
                                 comp.get('thickness', 0.5)))

        elif ctype in ('Concave Paraboloid', 'Convex Paraboloid'):
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("a Parameter", "a", comp.get('a', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("b Parameter", "b", comp.get('b', 1.0)))
            if ctype == 'Concave Paraboloid':
                self.propertyGrid_Properties.Append(
                    pg.FloatProperty("Center Hole Radius", "centerHoleRadius",
                                     comp.get('centerHoleRadius', 0.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("xTilt (deg)", "xTilt",
                                 comp.get('xTilt', 0.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("yTilt (deg)", "yTilt",
                                 comp.get('yTilt', 0.0)))

        elif ctype == 'Parabolic Surface':
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("a Parameter", "a", comp.get('a', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("b Parameter", "b", comp.get('b', 1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("c Parameter", "c", comp.get('c', -1.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Center Hole Radius", "centerHoleRadius",
                                 comp.get('centerHoleRadius', 0.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("xTilt (deg)", "xTilt",
                                 comp.get('xTilt', 0.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("yTilt (deg)", "yTilt",
                                 comp.get('yTilt', 0.0)))

        elif ctype == 'Spherical Surface':
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("Radius of Curvature", "radius_of_curvature",
                                 comp.get('radius_of_curvature', 5.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("xTilt (deg)", "xTilt",
                                 comp.get('xTilt', 0.0)))
            self.propertyGrid_Properties.Append(
                pg.FloatProperty("yTilt (deg)", "yTilt",
                                 comp.get('yTilt', 0.0)))

        # Medium enum helpers
        def _medium_enum(label, prop_name, default):
            idx = media_choices.index(comp.get(prop_name, default)) \
                if comp.get(prop_name, default) in media_choices else 0
            self.propertyGrid_Properties.Append(
                pg.EnumProperty(label, prop_name,
                                media_choices,
                                list(range(len(media_choices))),
                                idx))

        def _color_enum(label, prop_name, default):
            idx = color_choices.index(comp.get(prop_name, default)) \
                if comp.get(prop_name, default) in color_choices else 0
            self.propertyGrid_Properties.Append(
                pg.EnumProperty(label, prop_name,
                                color_choices,
                                list(range(len(color_choices))),
                                idx))

        default_after = 'BK7' if 'Lens' in ctype else 'Air'
        _medium_enum("Medium Before", "mediumBefore", 'Air')
        _medium_enum("Medium After",  "mediumAfter",  default_after)
        _color_enum("Color", "color", 'lightblue')

    # ══ Simulation ══════════════════════════════════════════════════════════════
    def rebuild_system(self):
        """Clear the scene, rebuild all components, trace rays, update plots."""

        # 1. Remove user visuals from 3-D canvas
        for child in list(self.optics_canvas.view.scene.children):
            if child not in self.base_visuals:
                child.parent = None

        if not self.components:
            self.optics_canvas.canvas.update()
            self.m_statusBar1.SetStatusText("No components in system.")
            return

        # 2. Instantiate component objects from self.components dicts
        objs = []
        try:
            for c in self.components:
                ctype = c['type']
                pt = Point((0.0, 0.0, c.get('center_z', 0.0)),
                           parentCanvas=self.optics_canvas)
                color = Color(c.get('color', 'lightblue'))

                if ctype == 'Spherical Lens':
                    obj = SphericalLens(
                        R1=c.get('R1', 2.0),
                        R2=c.get('R2', -2.0),
                        center=pt,
                        radius=c.get('radius', 1.0),
                        thickness=c.get('thickness', 0.6),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'BK7'),
                        color=color,
                        parentCanvas=self.optics_canvas)

                elif ctype == 'Parabolic Lens':
                    obj = ParabolicLens(
                        a=c.get('a', 1.0),
                        b=c.get('b', 1.0),
                        c_front=c.get('c_front', -1.0),
                        c_back=c.get('c_back', 1.0),
                        center=pt,
                        radius=c.get('radius', 1.0),
                        thickness=c.get('thickness', 0.5),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'BK7'),
                        color=color,
                        parentCanvas=self.optics_canvas)

                elif ctype == 'Concave Paraboloid':
                    obj = Concave_Paraboloid(
                        a=c.get('a', 1.0),
                        b=c.get('b', 1.0),
                        center=pt,
                        radius=c.get('radius', 1.0),
                        centerHoleRadius=c.get('centerHoleRadius', 0.0),
                        xTilt=c.get('xTilt', 0.0),
                        yTilt=c.get('yTilt', 0.0),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'Air'),
                        color=color,
                        parentCanvas=self.optics_canvas)

                elif ctype == 'Convex Paraboloid':
                    obj = Convex_Paraboloid(
                        a=c.get('a', 1.0),
                        b=c.get('b', 1.0),
                        center=pt,
                        radius=c.get('radius', 1.0),
                        xTilt=c.get('xTilt', 0.0),
                        yTilt=c.get('yTilt', 0.0),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'Air'),
                        color=color,
                        parentCanvas=self.optics_canvas)

                elif ctype == 'Parabolic Surface':
                    obj = Parabolic_Surface(
                        a=c.get('a', 1.0),
                        b=c.get('b', 1.0),
                        c=c.get('c', -1.0),
                        center=pt,
                        radius=c.get('radius', 1.0),
                        centerHoleRadius=c.get('centerHoleRadius', 0.0),
                        xTilt=c.get('xTilt', 0.0),
                        yTilt=c.get('yTilt', 0.0),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'Air'),
                        color=color,
                        parentCanvas=self.optics_canvas)

                elif ctype == 'Spherical Surface':
                    obj = Spherical_Surface(
                        radius_of_curvature=c.get('radius_of_curvature', 5.0),
                        center=pt,
                        aperture_radius=c.get('radius', 1.0),
                        xTilt=c.get('xTilt', 0.0),
                        yTilt=c.get('yTilt', 0.0),
                        mediumBefore=c.get('mediumBefore', 'Air'),
                        mediumAfter=c.get('mediumAfter', 'Air'),
                        color=color,
                        parentCanvas=self.optics_canvas)
                else:
                    continue

                objs.append(obj)

        except Exception as e:
            self.m_statusBar1.SetStatusText(f"Component build failed: {e}")
            return

        # 3. Build OpticalSystem from the list of component objects
        system = OpticalSystem(objs)

        # 4. Determine image-plane Z (with optional auto-focus)
        z_image = self.global_settings.get('z_image', 5.0)
        if self.global_settings.get('auto_focus', True):
            try:
                z_max = max(15.0,
                            self.components[-1]['center_z'] + 15.0)
                best_z, _ = system.find_best_focus(
                    Ray=Ray, Point=Point,
                    wavelength=0.530,
                    z_min=0.0, z_max=z_max, n_steps=100,
                    pupil_radius=self.global_settings['pupil_radius'],
                    z_start=self.global_settings['z_start'])
                if best_z is not None:
                    z_image = best_z
                    self.global_settings['z_image'] = z_image
                    prop = self.propertyGrid_Properties.GetProperty("z_image")
                    if prop:
                        prop.SetValue(z_image)
            except Exception as e:
                self.m_statusBar1.SetStatusText(f"Auto-focus failed: {e}")

        # 5. Trace visualisation rays (fan in Y and X directions)
        pupil_r  = self.global_settings['pupil_radius']
        z_start  = self.global_settings['z_start']
        fan_coords = np.linspace(-pupil_r, pupil_r, 5)

        try:
            for name, wl in self.wavelengths.items():
                # Tangential fan (Y-axis)
                for y in fan_coords:
                    ray = Ray(
                        Point((0.0, y, z_start),
                              parentCanvas=self.optics_canvas),
                        rayDirection=(0, 0, 1), dc=True,
                        wavelength=wl, color=name,
                        parentCanvas=self.optics_canvas)
                    out = system.trace_ray(ray)
                    if out is not None:
                        hit = OpticalSystem.intersect_ray_with_z_plane(
                            out, z_image)
                        if hit is not None:
                            out.update_Ray(hit)
                        else:
                            out.extend_Vector(2.0)

                # Sagittal fan (X-axis, skip centre – already in tangential)
                for x in fan_coords:
                    if abs(x) < 1e-9:
                        continue
                    ray = Ray(
                        Point((x, 0.0, z_start),
                              parentCanvas=self.optics_canvas),
                        rayDirection=(0, 0, 1), dc=True,
                        wavelength=wl, color=name,
                        parentCanvas=self.optics_canvas)
                    out = system.trace_ray(ray)
                    if out is not None:
                        hit = OpticalSystem.intersect_ray_with_z_plane(
                            out, z_image)
                        if hit is not None:
                            out.update_Ray(hit)
                        else:
                            out.extend_Vector(2.0)

        except Exception as e:
            self.m_statusBar1.SetStatusText(f"Ray tracing failed: {e}")

        # 6. Spot diagram
        try:
            spot_data = system.compute_spot_diagram(
                Ray=Ray, Point=Point,
                wavelengths=self.wavelengths,
                z_image=z_image,
                pupil_radius=pupil_r,
                z_start=z_start,
                direction=(0, 0, 1),
                canvas=None,
                n_rings=6)
            self.update_spot_diagram(spot_data, self.wavelengths)
        except Exception as e:
            self.m_statusBar1.SetStatusText(f"Spot diagram failed: {e}")

        # 7. Ray-fan diagram
        try:
            self.update_ray_fan_diagram(
                system, self.wavelengths, z_image, pupil_r)
        except Exception as e:
            self.m_statusBar1.SetStatusText(f"Ray fan diagram failed: {e}")

        self.optics_canvas.canvas.update()
        self.m_statusBar1.SetStatusText(
            f"Simulation updated  (Focal plane Z = {z_image:.3f})")

    # ── Plot helpers ─────────────────────────────────────────────────────────
    def update_spot_diagram(self, spot_data, wavelengths):
        """Rebuild the spot-diagram VisPy canvas inside the notebook tab."""
        self.spot_sizer.Clear(True)
        self.spot_plot = SpotDiagramPlot(
            spot_data, wavelengths=wavelengths,
            sizes=(400, 400),
            parent=self.panel_SpotDiagram)
        self.spot_sizer.Add(self.spot_plot.native, 1,
                            wx.EXPAND | wx.ALL, 5)
        self.panel_SpotDiagram.Layout()

    def update_ray_fan_diagram(self, system, wavelengths, z_image,
                               pupil_radius):
        """Rebuild the tangential + sagittal ray-fan plots."""
        self.rayfan_sizer.Clear(True)

        self.tan_plot = wx_VispyPlotCanvas(
            parent=self.panel_RayFanDiagram,
            plot_title="Tangential Fan (Ey vs Py)",
            x_axis_label="Normalised Pupil Y", y_axis_label="Ey",
            x_lim=(-1.0, 1.0), y_lim=(-0.05, 0.05))
        self.sag_plot = wx_VispyPlotCanvas(
            parent=self.panel_RayFanDiagram,
            plot_title="Sagittal Fan (Ex vs Px)",
            x_axis_label="Normalised Pupil X", y_axis_label="Ex",
            x_lim=(-1.0, 1.0), y_lim=(-0.05, 0.05))

        self.rayfan_sizer.Add(self.tan_plot.native, 1,
                              wx.EXPAND | wx.ALL, 5)
        self.rayfan_sizer.Add(self.sag_plot.native, 1,
                              wx.EXPAND | wx.ALL, 5)
        self.panel_RayFanDiagram.Layout()

        pupil_coords = np.linspace(-pupil_radius, pupil_radius, 41)
        norm_pupil   = pupil_coords / pupil_radius
        z_start      = self.global_settings['z_start']

        for name, wl in wavelengths.items():
            rgba = wavelength_to_rgb(wl)

            # Tangential fan
            tan_aber = []
            for py in pupil_coords:
                ray = Ray(Point((0.0, py, z_start)),
                          rayDirection=(0, 0, 1), dc=True,
                          wavelength=wl, color=name, parentCanvas=None)
                out = system.trace_ray(ray)
                if out is not None:
                    hit = system.intersect_ray_with_z_plane(out, z_image)
                    tan_aber.append(hit[1] if hit is not None else np.nan)
                else:
                    tan_aber.append(np.nan)

            # Sagittal fan
            sag_aber = []
            for px in pupil_coords:
                ray = Ray(Point((px, 0.0, z_start)),
                          rayDirection=(0, 0, 1), dc=True,
                          wavelength=wl, color=name, parentCanvas=None)
                out = system.trace_ray(ray)
                if out is not None:
                    hit = system.intersect_ray_with_z_plane(out, z_image)
                    sag_aber.append(hit[0] if hit is not None else np.nan)
                else:
                    sag_aber.append(np.nan)

            tan_aber = np.array(tan_aber)
            sag_aber = np.array(sag_aber)

            valid_tan = ~np.isnan(tan_aber)
            valid_sag = ~np.isnan(sag_aber)

            if np.any(valid_tan):
                mx = max(np.max(np.abs(tan_aber[valid_tan])), 1e-4)
                self.tan_plot.y_lim = (-mx * 1.2, mx * 1.2)
                self.tan_plot.plot_xy(
                    norm_pupil[valid_tan], tan_aber[valid_tan],
                    color=rgba)

            if np.any(valid_sag):
                mx = max(np.max(np.abs(sag_aber[valid_sag])), 1e-4)
                self.sag_plot.y_lim = (-mx * 1.2, mx * 1.2)
                self.sag_plot.plot_xy(
                    norm_pupil[valid_sag], sag_aber[valid_sag],
                    color=rgba)

    # ══ Event handlers ══════════════════════════════════════════════════════════
    def OnPropertyGridChange(self, event):
        prop = event.GetProperty()
        if not prop:
            return
        name = prop.GetName()
        val  = prop.GetValue()
        # Enum properties return an integer index – convert to string label
        if isinstance(prop, pg.EnumProperty):
            val = prop.GetChoices().GetLabel(val)

        if self.selected_index < 0:
            self.global_settings[name] = val
        else:
            self.components[self.selected_index][name] = val
            if name == "name":
                self.update_list_views()

        self.rebuild_system()

    def m_listBox_lst_componentsOnSelect(self, event):
        self.select_component(event.GetSelection())

    def m_treeCtrl1OnTreeSelChanged(self, event):
        item = event.GetItem()
        if not item.IsOk() or item == self.tree_root:
            self.select_component(-1)
            return
        # Walk children to find the index
        curr, _ = self.m_treeCtrl1.GetFirstChild(self.tree_root)
        idx = 0
        while curr.IsOk():
            if curr == item:
                self.select_component(idx)
                return
            curr = self.m_treeCtrl1.GetNextSibling(curr)
            idx += 1

    def m_button_add_componentOnButtonClick(self, event):
        ctype = self.m_comboBox1.GetValue()
        new_comp = self._load_config(ctype)
        count = sum(1 for c in self.components
                    if c.get('type') == ctype) + 1
        new_comp['name'] = f"{ctype} {count}"
        if self.components:
            new_comp['center_z'] = self.components[-1]['center_z'] + 1.5
        self.animate_gauge()
        self.components.append(new_comp)
        self.update_list_views()
        self.select_component(len(self.components) - 1)
        self.rebuild_system()

    def m_button_upOnButtonClick(self, event):
        idx = self.selected_index
        if 0 < idx < len(self.components):
            self.components[idx], self.components[idx - 1] = \
                self.components[idx - 1], self.components[idx]
            self.update_list_views()
            self.select_component(idx - 1)
            self.rebuild_system()

    def m_button_downOnButtonClick(self, event):
        idx = self.selected_index
        if 0 <= idx < len(self.components) - 1:
            self.components[idx], self.components[idx + 1] = \
                self.components[idx + 1], self.components[idx]
            self.update_list_views()
            self.select_component(idx + 1)
            self.rebuild_system()

    def m_button_removeOnButtonClick(self, event):
        idx = self.selected_index
        if 0 <= idx < len(self.components):
            self.components.pop(idx)
            self.update_list_views()
            self.select_component(min(idx, len(self.components) - 1))
            self.rebuild_system()

    def OnExampleSelect(self, event):
        selections = self.m_listBox2.GetSelections()
        sel = self.m_listBox2.GetString(selections[0]) \
              if selections else "Biconvex Lens Focus"
        self.animate_gauge()
        if sel == "Biconvex Lens Focus":
            self.load_biconvex_preset()
        elif sel == "Apochromatic Triplet":
            self.load_apochromatic_preset()
        elif sel == "Cooke Triplet":
            self.load_cooke_preset()
        self.update_list_views()
        self.select_component(-1)
        self.rebuild_system()

    def m_button_add_py_egOnButtonClick(self, event):
        """Load and run a standalone Python example script inside the GUI."""
        default_dir = os.path.join(
            os.getcwd(), "opticsLAB", "raytracing", "testCases")
        if not os.path.exists(default_dir):
            default_dir = os.getcwd()

        with wx.FileDialog(
                self, "Select Python Example File",
                defaultDir=default_dir,
                wildcard="Python files (*.py)|*.py",
                style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            path = dlg.GetPath()

        # Clear state
        self.components = []
        self.update_list_views()
        self.selected_index = -1
        self.update_property_grid()
        for child in list(self.optics_canvas.view.scene.children):
            if child not in self.base_visuals:
                child.parent = None
        self.spot_sizer.Clear(True)
        self.rayfan_sizer.Clear(True)
        self.panel_SpotDiagram.Layout()
        self.panel_RayFanDiagram.Layout()
        self.animate_gauge()

        # Thin mock classes so example scripts render into the GUI panels
        gui_self = self

        class MockOpticsLabCanvas:
            def __init__(self, bgColor="lightsteelblue", *a, **kw):
                self.canvas = gui_self.optics_canvas.canvas
                self.view   = gui_self.optics_canvas.view
            def show(self):
                self.canvas.show()

        class MockSpotDiagramPlot:
            def __init__(self, spot_data, wavelengths, *a, **kw):
                gui_self.update_spot_diagram(spot_data, wavelengths)
            def show(self):
                pass

        import vispy.app as _vapp
        import matplotlib.pyplot as _plt
        import opticsLAB.raytracing.component as _comp_mod
        import opticsLAB.raytracing.spotDiagram as _spot_mod
        import opticsLAB.raytracing.component.OpticsLabCanvas as _canvas_mod

        # Patch to redirect example visuals into the GUI
        orig_run        = _vapp.run
        orig_plt_show   = _plt.show
        orig_canvas_cls = _comp_mod.OpticsLabCanvas
        orig_canvas_mcls= _canvas_mod.OpticsLabCanvas
        orig_spot_cls   = _spot_mod.SpotDiagramPlot

        _vapp.run                            = lambda *a, **kw: None
        _plt.show                            = lambda *a, **kw: None
        _comp_mod.OpticsLabCanvas            = MockOpticsLabCanvas
        _canvas_mod.OpticsLabCanvas          = MockOpticsLabCanvas
        _spot_mod.SpotDiagramPlot            = MockSpotDiagramPlot

        try:
            with open(path, 'r') as f:
                exec(f.read(), {'__file__': path, '__name__': '__main__'})
            self.m_statusBar1.SetStatusText(
                f"Loaded: {os.path.basename(path)}")
        except Exception as e:
            wx.MessageBox(f"Error running example:\n{e}",
                          "Error", wx.OK | wx.ICON_ERROR)
            self.m_statusBar1.SetStatusText("Error running example.")
        finally:
            _vapp.run               = orig_run
            _plt.show               = orig_plt_show
            _comp_mod.OpticsLabCanvas   = orig_canvas_cls
            _canvas_mod.OpticsLabCanvas = orig_canvas_mcls
            _spot_mod.SpotDiagramPlot   = orig_spot_cls

        self.optics_canvas.canvas.update()

    # ── Menu callbacks ────────────────────────────────────────────────────────
    def openProjectOnMenuSelection(self, event):
        self.m_button_btn_load_tomlOnButtonClick(event)

    def saveProjectOnMenuSelection(self, event):
        self.m_button_btn_save_tomlOnButtonClick(event)

    def quitOnMenuSelection(self, event):
        self.Close()

    def concaveLensOnMenuSelection(self, event):
        new_comp = self._load_config('Spherical Lens')
        new_comp['name'] = f"Concave Lens {len(self.components) + 1}"
        new_comp['R1'], new_comp['R2'] = -2.0, 2.0
        if self.components:
            new_comp['center_z'] = self.components[-1]['center_z'] + 1.5
        self.animate_gauge()
        self.components.append(new_comp)
        self.update_list_views()
        self.select_component(len(self.components) - 1)
        self.rebuild_system()

    def convexLensOnMenuSelection(self, event):
        new_comp = self._load_config('Spherical Lens')
        new_comp['name'] = f"Convex Lens {len(self.components) + 1}"
        new_comp['R1'], new_comp['R2'] = 2.0, -2.0
        if self.components:
            new_comp['center_z'] = self.components[-1]['center_z'] + 1.5
        self.animate_gauge()
        self.components.append(new_comp)
        self.update_list_views()
        self.select_component(len(self.components) - 1)
        self.rebuild_system()

    def parabolicMirrorOnMenuSelection(self, event):
        new_comp = self._load_config('Concave Paraboloid')
        new_comp['name'] = f"Parabolic Mirror {len(self.components) + 1}"
        if self.components:
            new_comp['center_z'] = self.components[-1]['center_z'] + 1.5
        self.animate_gauge()
        self.components.append(new_comp)
        self.update_list_views()
        self.select_component(len(self.components) - 1)
        self.rebuild_system()

    def sphericalMirrorOnMenuSelection(self, event):
        new_comp = self._load_config('Spherical Surface')
        new_comp['name'] = f"Spherical Mirror {len(self.components) + 1}"
        new_comp['radius_of_curvature'] = -5.0
        if self.components:
            new_comp['center_z'] = self.components[-1]['center_z'] + 1.5
        self.animate_gauge()
        self.components.append(new_comp)
        self.update_list_views()
        self.select_component(len(self.components) - 1)
        self.rebuild_system()

    def spotDiagramOnMenuSelection(self, event):
        self.notebook.SetSelection(0)

    def rayFanDiagramOnMenuSelection(self, event):
        self.notebook.SetSelection(1)

    def aboutOnMenuSelection(self, event):
        wx.MessageBox(
            "Optics Lab Interactive GUI\n"
            "Built with wxPython and VisPy.\n\n"
            "Simulate custom optical systems with real-time 3-D ray tracing,\n"
            "spot diagrams, and aberration ray fans.",
            "About Optics Lab", wx.OK | wx.ICON_INFORMATION)

    # ── TOML load / save ──────────────────────────────────────────────────────
    def m_button_btn_load_tomlOnButtonClick(self, event):
        with wx.FileDialog(
                self, "Load Optical System File",
                wildcard="TOML files (*.toml)|*.toml",
                style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            path = dlg.GetPath()
        try:
            self.animate_gauge()
            data = self._load_toml(path)
            if 'global' in data:
                self.global_settings.update(data['global'])
            if 'components' in data:
                self.components = data['components']
            self.update_list_views()
            self.select_component(-1)
            self.rebuild_system()
            self.m_statusBar1.SetStatusText(
                f"Loaded: {os.path.basename(path)}")
        except Exception as e:
            wx.MessageBox(f"Failed to load file:\n{e}",
                          "Error", wx.OK | wx.ICON_ERROR)

    def m_button_btn_save_tomlOnButtonClick(self, event):
        with wx.FileDialog(
                self, "Save Optical System File",
                wildcard="TOML files (*.toml)|*.toml",
                style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            path = dlg.GetPath()
        try:
            self._save_toml(path,
                            {'global': self.global_settings,
                             'components': self.components})
            self.m_statusBar1.SetStatusText(
                f"Saved: {os.path.basename(path)}")
        except Exception as e:
            wx.MessageBox(f"Failed to save file:\n{e}",
                          "Error", wx.OK | wx.ICON_ERROR)

    def _save_toml(self, filepath, data):
        """Write a minimal TOML file from a dict with 'global' and 'components'."""
        def _fmt(v):
            if isinstance(v, str):   return f'"{v}"'
            if isinstance(v, bool):  return str(v).lower()
            return str(v)

        with open(filepath, 'w') as f:
            f.write("[global]\n")
            for k, v in data.get('global', {}).items():
                f.write(f"{k} = {_fmt(v)}\n")
            f.write("\n")
            for comp in data.get('components', []):
                f.write("[[components]]\n")
                for k, v in comp.items():
                    f.write(f"{k} = {_fmt(v)}\n")
                f.write("\n")

    def _load_toml(self, filepath):
        """Parse a minimal TOML file and return a dict."""
        data = {'global': {}, 'components': []}
        section = None
        current = {}

        with open(filepath, 'r') as f:
            for raw in f:
                line = raw.strip()
                if not line or line.startswith('#'):
                    continue
                if line == "[[components]]":
                    if section == 'components' and current:
                        data['components'].append(current)
                    current = {}
                    section = 'components'
                elif line.startswith('[') and line.endswith(']'):
                    if section == 'components' and current:
                        data['components'].append(current)
                    inner = line[1:-1]
                    if inner == 'global':
                        section = 'global'
                        current = data['global']
                else:
                    m = re.match(r'^([^=]+)=(.*)$', line)
                    if m:
                        key = m.group(1).strip()
                        vs  = m.group(2).strip()
                        if vs.startswith('"') and vs.endswith('"'):
                            val = vs[1:-1]
                        elif vs.lower() == 'true':
                            val = True
                        elif vs.lower() == 'false':
                            val = False
                        else:
                            try:
                                fval = float(vs)
                                val  = int(fval) if fval.is_integer() else fval
                            except ValueError:
                                val = vs
                        current[key] = val

        if section == 'components' and current:
            data['components'].append(current)
        return data


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    app = wx.App(False)
    frame = OpticsLabGuiApp(None)
    frame.Show(True)
    app.MainLoop()