[detector]
type='Detector'
"type@help"= "Detector documentation follows"
"type_readonly" = true
name="Detector_1"
"name@help"="Name of the detector for reference (optional)"
description=""
"description@help"="User notes for the retarder"
theta=-45.0
"theta@help"="Orientation of the detector in degrees. Check radians property to True if you want to enter in radians."
theta_radians=false
"theta_radians@help"="Check if theta is in Radians"
color="Blue"
"color@help"="Color used for representation in the GUI"
"color%display"="namesList"
enabled=true
"enabled@help"="Whether the component should be included for calculations. Included if True."