[component]
# Remove first letter capitals
type='Polariser'
"type@help"= "Polariser documentation follows"
"type_readonly" = true
name="Polariser_1"
"name@help"="Name of the polariser for reference (optional)"
description="This is the retarder Description"
"description@help"="User notes for the polariser"
theta=45.0
"theta@help"="Orientation of the polariser in degrees. Check radians property to True if you want to enter in radians."
radians=false
"radians@help"="Check if theta is in radians"
mueller= [[1.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0]]
"mueller@help"="Mueller matrix of the component"
#jones=[]#[[1.0,1.0],[1.0,1.0]]
"mones@help"="Jones matrix of the component"
color="Blue"
"color@help"="Color used for representation in the GUI"
"color%display"="colorWidget"
enabled=true
"enabled@help"="Whether the component should be included for calculations. Included if True."